name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20.12.2-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the site
        run: |
          npm install
          npm run build
          apk update && apk add git
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.APP_TOKEN }}
          publish_dir: ./dist